name: Build MMOCore

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu-jdk'
          cache: 'maven'
      
      - name: Build with Maven
        run: mvn -B clean package
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MMOCore-${{ github.sha }}
          path: target/MMOCore-*.jar
          
  # Release job
  release:
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: MMOCore-${{ github.sha }}
          path: dist
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/MMOCore-*.jar
          name: MMOCore ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
